### ISSUE TITLE
Criar teste funcionais e de unidade para o gateway server

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/balaio#102]
As views do gateway server não está testada, foi realizado um esforço entre @robertatakenaka e @jamilatta para realizar esses testes porém sem sucesso.

**Comment by robertatakenaka** [comment]
Estou trabalhando nos testes de ArticlePkg API e Attempt API
https://github.com/robertatakenaka/balaio/tree/91

Mas notem que este ainda não está merged com https://github.com/robertatakenaka/jamilatta/tree/gateway (ou seja, https://github.com/scieloorg/balaio/pull/104)
