### ISSUE TITLE
API resource URI está errado para objetos single 

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/balaio#107]
A API está retornando um endereço errado para os objetos single: 

``` json
{
article_title: "jamil",
issue_year: 2012,
journal_title: "Brasilian of Magic",
journal_pissn: "123",
journal_eissn: "321",
issue_suppl_number: "33",
attempts: [
"/api/v1/attempts/2/",
"/api/v1/attempts/3/",
"/api/v1/attempts/4/"
],
issue_suppl_volume: "22",
issue_volume: "10",
resource_uri: "/api/v1/packages/2/2",
id: 2,
issue_number: "20"
}
```

**Comment by gustavofonseca** [comment]
Não entendi... o que é um objeto _single_

On Mon, Sep 16, 2013 at 2:35 PM, Jamil Atta Junior <notifications@github.com

**Comment by jamilatta** [comment]
É um recurso para um item.

On Mon, Sep 16, 2013 at 2:40 PM, Gustavo Fonseca
notifications@github.comwrote:

> Não entendi... o que é um objeto _single_
> 
> On Mon, Sep 16, 2013 at 2:35 PM, Jamil Atta Junior <
> notifications@github.com
> 
> > wrote:
> > 
> > A API está retornando um endereço errado para os objetos single:
> > 
> > {article_title: "jamil",issue_year: 2012,journal_title: "Brasilian of
> > Magic",journal_pissn: "123",journal_eissn: "321",issue_suppl_number:
> > "33",attempts:
> > ["/api/v1/attempts/2/","/api/v1/attempts/3/","/api/v1/attempts/4/"],issue_suppl_volume:
> > "22",issue_volume: "10",resource_uri: "/api/v1/packages/2/2",id:
> > 2,issue_number: "20"}
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/scieloorg/balaio/issues/107>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/scieloorg/balaio/issues/107#issuecomment-24529014
> .

## 

Atenciosamente,

Jamil Atta Junior

**Comment by jamilatta** [comment]
Esse bug havia sido resolvido, porém após modificações no renderer voltou a aparecer, criei os testes para a api com esses erros "conhecido".

**Comment by jamilatta** [comment]
Os testes para esses erros "conhecidos" foram ajustados e o bug corrigido.
