### ISSUE TITLE
Gateway HTTP API: definições de obrigatoriedade dos parâmetros de filtro

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/balaio#115]
1. Validations.all() teria como filtro obrigatório articlepkg_id e attempt_id?
2. Tickets.all() teria como filtro obrigatório articlepkg_id?

Nota: Removi do Attempts o filtro obrigatório articlepkg_id porque é possível querer resgatar todos os attempts ocorridos em um determinado período, independentemente de saber de que artigo, por isso a não obrigatoriedade de articlepkg_id.

Para tickets, talvez seja a mesma lógica.

No entanto, para Validations, acho que não faz sentido listar sem ter o articlepkg_id + attempt_id. No entanto, talvez para gerar um relatório dos erros mais comuns?

Dependendo da conclusão a documentação terá que ser revisada.

**Comment by gustavofonseca** [comment]
Esse ticket foi desconsiderado pois as mudanças recentes levaram a isso. Os tipos de entidade não existem mais.
