### ISSUE TITLE
Modelos Ticket e Comment - sugestão de novos dados

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/balaio#119]
Me parece que precisaríamos ter no ticket novas colunas: title e quem abriu o ticket. E se sim, o que poderia ser? o nome do usuario ou um id?

Além disso, no modelo de comments também estaria faltando data e autor do comentario (que pode ser a "prestadora" e alguém da produção.

Concordam?

**Comment by gustavofonseca** [comment]
De acordo. Penso que podemos usar o email dos usuários como identificador.

**Comment by gustavofonseca** [comment]
As conclusões foram implementadas
