### ISSUE TITLE
[periódico] journal-id/@journal-id-type="nlm-ta" para títulos NLM/Medline

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/balaio#15]
Os periódicos que estão registrados na NLM/Medline devem ter o elemento journal-id com @journal-id-type=nlm-ta e o valor deve ser o mesmo registrado na NLM.

Para isso, a fonte primaria é: http://www.ncbi.nlm.nih.gov/nlmcatalog e as fontes secundarias: title manager (v421) ou scielo manager.

**Comment by gustavofonseca** [comment]
Precisamos avaliar se a NLM disponibiliza esta consulta em algum dos web
services listados em http://www.nlm.nih.gov/api/

2013/6/10 Roberta Takenaka notifications@github.com

**Comment by robertatakenaka** [comment]
It was considered medline_title of
http://docs.scielo.org/projects/scielo-manager/en/latest/dev/journals-api.html#get-a-single-journal

I have found no NLM API (http://www.nlm.nih.gov/api/) which returns data of journals
