### ISSUE TITLE
Padronização dos textos das mensagens de notificação.

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/balaio#155]
Atualmente existe uma variedade de frases para notificar coisas semelhantes, exemplo:
- journal has no NLM journal title
- missing abbreviated title in xml
- no funding-group and no ack
- tag reference missing

Eu sugiro que sejam definidas frases padronizadas, exemplo:
- Missing data: NLM journal title.
- Missing data: Abbreviated title.
- Missing data: Funding-group, ack.
- Missing data: Tag reference.

**Comment by gustavofonseca** [comment]
Detalhe, precisamos pensar em todos os tipos de mensagens que podem ser enviadas. Por hora eu vejo:

Quanto à existência dos dados:
- Dados faltantes 
- Dados completos

Quanto à qualidade dos dados:
- Dados corretos
- Dados incorretos

**Comment by robertatakenaka** [comment]
No entanto, há casos que apesar dos dados inexistirem, não significa erro. Mesmo asism podemos dizer "Missing"? Ou mais adequado, "Not found"? No caso de funding-group and ack, são itens não obrigatórios. Indicar sua inexistência é com a finalidade de observar se o dado existe e não foi identificado como tal. Qual seria a melhor mensagem para isto?

**Comment by gustavofonseca** [comment]
Talvez esse caso possa usar o mesmo texto de _Missing_, mas com o status ==
warning.

2013/10/18 Roberta Takenaka notifications@github.com
