### ISSUE TITLE
Balaio retorna erro quando param `debug=True`

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/balaio#157]
No modo de debug o balaio apresenta problemas para desempacotar as mensagens  entre os PIPES, as mensagens de debug estão chegando para o recv_message e ele não sabe tratar isso.

**Comment by gustavofonseca** [comment]
Sim, isso é fato pq o stream stdout é utilizado no IPC. Essa é a motivação do ticket #120.

**Comment by jamilatta** [comment]
Esse ticket se tornou invalido no momento em que o unix domain socket foi desenvovido.
