### ISSUE TITLE
Teste do balaio faltando: `article-title`

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/balaio#158]
Erro no balaio quando falta o `article-title`.

``` python
Traceback: (IntegrityError) articlepkg.article_title may not be NULL u'INSERT INTO 
articlepkg (article_title, journal_pissn, journal_eissn, journal_title, issue_year, 
issue_volume, issue_number, issue_suppl_volume, issue_suppl_number) VALUES
(?, ?, ?, ?, ?, ?, ?, ?, ?)' (None, '1518-8787', '0034-8910', u'Revista de Sa\xfade
 P\xfablica', '2013', '47', None, '2', None)
```

**Comment by jamilatta** [comment]
Neste caso o checkin deve garantir a existência dessa tag.

**Comment by jamilatta** [comment]
Após erro de integridade a aplicação passa a somente realizar o monitoramento dos pacotes.

**Comment by gustavofonseca** [comment]
Eu não acho que o checkin deva garantir a existência desse dado. A etapa
checkin apenas deve garantir a produção de um objeto _models.Attempt_ seja
ele válido ou não. O fato da falta de atributos obrigatórios para
_models.ArticlePkg_ deve simplesmente gerar uma instância de
_models.Attempt_ com o atributo _is_valid==False_ e sem a relação com um
_ArticlePkg_.

**Comment by jamilatta** [comment]
Talvez não tenha entendido: na função get_attempt() precisamos garantir que não seja "commitado" um package sem esses atributos obrigatórios, estou adicionado essa validação e marcando o atributo `is_valid=False`

**Comment by jamilatta** [comment]
Desconsiderar a msg anterior método get_from_package realiza essa validação.
