### ISSUE TITLE
Invalidar attempt quando a identificação do fascículo não é possível (complemento ao #158)

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/balaio#162]
Para que o attempt seja válido, o package.meta deveria ter pelo menos um dos itens abaixo existente:

issue_volume
issue_number
issue_suppl_volume
issue_suppl_number

Ajustar também ArticlePkg.get_or_create_from_package para que o ArticlePkg seja devidamente identificado / recuperado. Artigos podem ter o mesmo título e serem completamente diferentes. É necessário considerar também o periódico e o fascículo.

**Comment by gustavofonseca** [comment]
Na realidade eu acho que a maneira mais sensata de pegar um ArticlePkg é buscando pelo _eissn_ ou _pissn_. Se o pacote não apresentar nenhum desses, deve ser invalidado.

**Comment by robertatakenaka** [comment]
Eu não entendi porque você acha isso. Buscar pelo eissn e/ou pissn, resultará em um monte de artigos, o que não seria suficiente para distingui-los. Imagine um artigo cujo nome é editorial. Um artigo com este nome apareceria em todos os fascículos de qualquer revista. Veja o #158. Como o article_title tampouco é o suficiente para fazer distinção, sugiro acrescentar também todos os dados presentes que identificam o fascículo issue number, issue volume, suplemento.

**Comment by robertatakenaka** [comment]
Da mesma forma, que foi identificado que a ausência do pkg.meta['article_title'] invalidava o attempt (attempt.is_valid = False), a mesma lógica deveria ser aplicada caso todos os pkg.meta['issue_number'], pkg.meta['issue_volume'], pkg.meta['suplementos'] igual a None. Pois, considerando que sem o issn + article title + identificacao do issue não seja possível a identificação de um único artigo, haverá falha na inserção do attempt.

**Comment by gustavofonseca** [comment]
@jamilatta, a discussão está dentro do escopo deste ticket.

@robertatakenaka, é verdade que o [pe]issn não é suficiente para identificar o fascículo alvo. Entretanto devemos utilizar uma composição de *[pe]issn + (issue_volume ou issue_number ou issue_suppl_volume ou issue_suppl_number)

**Comment by robertatakenaka** [comment]
sim, gustavo. No entanto, já existe a checagem de *[pe]issn, mas está faltando  (issue_volume ou issue_number ou issue_suppl_volume ou issue_suppl_number). Foi o que quis dizer.

``` python
if package.is_valid_package() and meta['article_title'] and (meta['journal_eissn'] or meta['journal_pissn']):
        attempt.is_valid = True

```

**Comment by gustavofonseca** [comment]
Fato, acho que eu to tumultuando só. =]
