### ISSUE TITLE
`sqlalchemy.exc.OperationalError: (OperationalError) database is locked` ao depositar diversos pacotes de uma só vez.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/balaio#165]
Utilizando minha VM realizei um teste de copia em massa de vários pacotes para a pasta monitorada pelo balaio e obtive o seguinte erro:

``` python
sqlalchemy.exc.OperationalError: (OperationalError) database is locked u'INSERT INTO checkpoint (started_at, ended_at, point, attempt_id) VALUES (?, ?, ?, ?)' ('2013-10-28 11:48:55.583815', None, 2, 2)
```

Após o erro o balaio.py o stdout apenas mostra eventos do monitor.py `IN_CLOSE_WRITE`

**Comment by gustavofonseca** [comment]
O sqlite não é um RDBMS com suporte a concorrência em leitura e escrita. Existem diversos modos de operação que modificam suas características. Veja http://www.sqlite.org/lockingv3.html

**Comment by jamilatta** [comment]
@robertatakenaka @fabiobatalha  

compartilhei com o @gustavofonseca meu experimento de copia em massa de pacotes utilizando o postgres como SGBD, e rolou legal, acredito que diminuiríamos problemas de "concorrência" e "lock" utilizando o postgres. 

Alguém tem alguma objeção em passarmos a utilizar o postgres como SGBD, reparem que a única diferença esta na DSN utilizada e no requeriments.txt que passa a ter o psycopg2 como dependência.

**Comment by robertatakenaka** [comment]
Nenhuma objeção.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br

---

Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

2013/10/30 Jamil Atta Junior notifications@github.com

> @robertatakenaka https://github.com/robertatakenaka @fabiobatalhahttps://github.com/fabiobatalha
> 
> compartilhei com o @gustavofonseca https://github.com/gustavofonsecameu experimento de copia em massa de pacotes utilizando o postgres como
> SGBD, e rolou legal, acredito que diminuiríamos problemas de "concorrência"
> e "lock" utilizando o postgres.
> 
> Alguém tem alguma objeção em passarmos a utilizar o postgres como SGBD,
> reparem que a única diferença esta na DSN utilizada e no requeriments.txt
> que passa a ter o psycopg2 como dependência.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/scieloorg/balaio/issues/165#issuecomment-27402174
> .

## 

 http://www.scielo15.org/
*
*
_SciELO 15 anos_
http://www.scielo15.org

**Comment by gustavofonseca** [comment]
Feito, migramos para postgresql.
