### ISSUE TITLE
Relatório de validação de pacote

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/balaio#174]
Escrever script que gera um relatório simples para ser enviado para a equipe da Javani para validação.

O relatório deve conter o resultado do processo de validação automática de um determinado pacote.

**Comment by jamilatta** [comment]
Por que essa atividade foi finalizada?

**Comment by gustavofonseca** [comment]
Pq eu escrevi um script que gera um relatório simples para ser enviado para a equipe da Javani para validação. Falha minha não ter registrado isso no ticket antes de fechá-lo.

https://gist.github.com/gustavofonseca/de5c892a94fd560d71cd#file-report-py
