### ISSUE TITLE
Criar filtro de attempts pelo atributo `package_checksum`

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/balaio#182]
Esse filtro se faz necessário quando desejamos verificar o resultado da validação de um determinado pacote que temos em mãos. Embora o atributo `package_checksum` possua restrição quanto a sua exclusividade, o resultado do filtro deve ser montado como se houvessem N ocorrências, para manter a consistência.

**Comment by jamilatta** [comment]
Somente para contextualizar, essa demanda é para a API do balaio?

**Comment by gustavofonseca** [comment]
Sim

**Comment by gustavofonseca** [comment]
Inacreditivelmente esta funcionalidade já estava implementada. É possível realizar filtro por qualquer atributo de uma entidade. Um sonho.

**Comment by jamilatta** [comment]
Legal.

On Fri, Nov 29, 2013 at 11:28 AM, Gustavo Fonseca
notifications@github.comwrote:

> Closed #182 https://github.com/scieloorg/balaio/issues/182.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/scieloorg/balaio/issues/182
> .

## 

Atenciosamente,

Jamil Atta Junior
