### ISSUE TITLE
Envio dos metadados do artigo para o Manager

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/balaio#218]
Depende do #210.

O resultado da extração dos metadados de um determinado xml SPS de artigo + urls dos arquivos estáticos deve ser enviado para o Manager, conforme a interface https://github.com/scieloorg/scielo-manager/blob/master/scielomanager/api/resources.py#L389

**Comment by jamilatta** [comment]
Tarefa realizado no módulo checkout.py.
