### ISSUE TITLE
[fascículo] article-meta/pub-date

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/balaio#22]
article-meta/pub-date é um elemento que pode ocorrer pelo menos uma vez.

Validar article-meta/pub-date, de modo que pelo menos uma das ocorrências de article-meta/pub-date deve ser equivalente a registrada nos dados do fascículo correspondente.
## 

Informações suplementares:
há pelo menos 1, com atributos:

Na versão 3.0:
@pub-type: 
- epub - quando documento é publicado online (ahead ou há somente em versão eletrônica)
- ppub - quando publicado tb na impressa/ no fascículo
- epub-ppub quando é periódico impresso/eletrônico

http://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/article/dobs.html#dob-dates

http://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/article/tags.html#el-pubdate

Validar também o conteúdo de day, year, month (numérico). Tem que ser correspondente ao fascículo. Há também season, quando é um período de meses, sendo válido as abreviações dos meses em inglês e também os nomes das estações do ano em inglês.

Na versão JATS 1.0, estão permitidos outros atributos:

@calendar Calendar

@date-type Type of Date 
Event in the lifecycle of an article that this date is marking (for example, the date the manuscript was received or accepted, the date the electronic preprint was published, or the date of any revision or retraction).
Values: accepted, received, rev-recd, rev-request

@iso-8601-date ISO-8601 Formatted Date

@pub-type Type of Publication
A combination of the format/medium of a document with one or more events from its lifecycle, for example, “epub” for publication in an electronic format or “ppub” for print publication.

@publication-format 
(Best Practice: This attribute should be used when the value is known. Values may include such formats as “print”, “electronic”, “video”, “audio”, “ebook”, “online-only”.)

@xml:lang Language

http://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/article/dobs.html#dob-dates

[pub-date] must have either [@pub-type] or [@date-type + @publication-format]. Do not use [@pub-type] with [@publication-format]

**Comment by leticiaquino** [comment]
Acrescentando..
Dependendo do periódico, considerar válido a identificação apenas da tag `<year>`. Verificar a possibilidade de emitir um Warning para esse caso.
Verificar em:
http://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/article/tags.html#el-pubdate
"This date may be a day/month/year, month/year, season/year, **or just year**."
