### ISSUE TITLE
Acesso ao conteúdo dos pacotes via interface http

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/balaio#228]
Criar os endpoints para os arquivos estáticos no `httpd.py`

**Comment by gustavofonseca** [comment]
Recursos:

Listar todos os membros de um Attempt:
    `/api/:api_id/files/:attempt_id/` 

Baixar um determinado membro:
    `/api/:api_id/files/:attempt_id/:target.zip/?file=:member`

Baixar mais de um membro:
    `/api/:api_id/files/:attempt_id/:target.zip/?file=:member&file=:member2`

Baixar todo o pacote:
    `/api/:api_id/files/:attempt_id/:target.zip/?full=true`
