### ISSUE TITLE
Refatoração da função *checkout.upload_static_files*

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/balaio#232]
Depois das novas implementações _(Attempt().analyzer.subzip)_ , o código do módulo _checkout_ pode ser simplificado em diversos pontos. Um deles é a função _checkout.upload_static_files_.

**Comment by jamilatta** [comment]
Sim, o método _checkout.upload_static_files_ pode ser beneficiado com essa nova abordagem.
