### ISSUE TITLE
Testes de integração do módulo checkout

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/balaio#238]

**Comment by jamilatta** [comment]
Estou realizando esses testes.

**Comment by jamilatta** [comment]
O método `pending_checkout` no `models.py` não esta retornando o esperado para o decorator @hybrid_property, por consequência a query para filtrar pelos itens disponíveis para checkout não funciona.

**Comment by jamilatta** [comment]
Testes realizados e tickets criados para realizar os ajustes.
