### ISSUE TITLE
[artigo-refencias] element-citation/@publication-type='journal'

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/balaio#26]
Quando element-citation/@publication-type='journal' são obrigatorios:
source (título do periódico)
article-title
year

**Comment by jamilatta** [comment]
Exemplo da tag que representa as referências:

``` xml
<ref-list>
  <title>REFERENCES</title>
  <ref id="B01">
    <mixed-citation>ANSARI A, THOMAS S and GOLDSMITH D. 2003. Assessing glycemic control in patients with diabetes and end-stage renal failure. Am J Kidney Dis 41: 523-531.</mixed-citation>
    <element-citation publication-type="journal">
        <person-group person-group-type="author">
            <name>
                <surname>ANSARI</surname>
                <given-names>A</given-names>
            </name>
            <name>
                <surname>THOMAS</surname>
                <given-names>S</given-names>
            </name>
            <name>
                <surname>GOLDSMITH</surname>
                <given-names>D</given-names>
            </name>
        </person-group>
        <year>2003</year>
        <article-title xml:lang="en">Assessing glycemic control in patients with diabetes and end-stage renal failure</article-title>
        <source xml:lang="en">Am J Kidney Dis</source>
        <volume>41</volume>
        <fpage>523</fpage>
        <lpage>531</lpage>
    </element-citation>
  </ref>
</ref-list>
```

**Comment by jamilatta** [comment]
Atividade realizada conforme descrito no ticket, o **pipe** verificar a existência das tags e dos conteúdos nas tags descritas acima e caso a lista de referências não exista o **pipe** retorna uma message de **warning**

**Comment by robertatakenaka** [comment]
Este código deve ser refatorado, pois tem-se que levar em consideração de que um artigo tem mais de uma referência e todas as referências devem ser analisadas. O código como está para quando encontra o primeiro erro.
O ideal é que para cada referência seja verificada as condições e a description tem que conter os "ID" das referências que não estão corretas.
Além disso, o ideal é que seja indicado se o problema está no source e/ou article-title e/ou year (4 dígitos) e não simplesmente dizer que um deles não está correto.

**Comment by robertatakenaka** [comment]
Este ticket foi dividido em 4: #66, #65, #64, #67
