### ISSUE TITLE
Validar estrutura <journal-meta> dos meta-dados da revista

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/balaio#279]
Todos os arquivos devem ter a seguinte estrutura para os meta-dados da revista:

```
<journal-meta>
    <journal-id journal-id-type="nlm-ta"><journal-id>
    <journal-title-group>
       <journal-title></journal-title>
       <abbrev-journal-title abbrev-type="publisher"></abbrev-journal-title>
    </journal-title-group>
    <issn pub-type="epub"></issn>
    <publisher>
    <publisher-name></publisher-name>
    </publisher>
</journal-meta>


Obs.: o valor de @journal-id-type pode mudar para "publisher-id". Veja a explicação abaixo:

Caso a revista esteja indexada no Medline devemos utilizar o valor "nlm-ta" e identificar o título abreviado NLM;

Caso a revista não esteja indexada ao Medline, utilizar o valor "publisher-id" e identificar o acrônimo da revista. Ex.:
<journal-id journal-id-type="publisher-id">rba<journal-id>


Adendo:

A revista pode apresentar dois ISSN: Online e impresso. Caso haja dois ISSNs considerar a seguinte estrutura:

[...]
</journal-title-group>
    <issn pub-type="ppub"></issn>
    <issn pub-type="epub"></issn>
    <publisher>
[...]

Verificar a possibilidade do programa conferir se a estrutura está correta.
```

**Comment by gustavofonseca** [comment]
@robertatakenaka @fabiobatalha @jamilatta não seria caso de uma maior restrição na XSD para a estrutura partindo de `<journal-meta>`?

**Comment by jamilatta** [comment]
Sim, acredito que devemos ter uma estrutura mais rígida.

**Comment by fabiobatalha** [comment]
Sim, Não tem nem como neste momento agente saber se a revista esta em NLM, PubMed, etc.... tampouco definir o publisher_id de todas essas bases, agente até pode pegar essa valor dos metadados do periódico, mas qual seria a finalidade? O PMC exige isso? ou agente que esta incluindo essa demanda?

Na verdade sempre achei que o journal-id-type devesse ser publisher-id com o ID da SciELO. Por qual motivo colocaríamos o publisher ID da NLM ou de um terceiro sendo que nós somos o publicador que esta produzindo os XML's?

**Comment by leticiaquino** [comment]
Olá Fábio,

acredito que tenhamos decidido inserir essa informação do título abreviado medline, pois na tagging guidelines há a seguinte informação:

"If the PubMed abbreviation is available, tag with @journal-id-type="nlm-ta""

http://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/article/tags.html#el-jid

**Comment by gustavofonseca** [comment]
Mas isso é importante apenas para a exportação para o PMC, certo? Eu acho importante a gente ter em mente que a carga de artigos no SciELO e a interoperação com o PMC são 2 problemas distintos, e com requisitos distintos. O caso do título abreviado medline pode ser inserido apenas no momento de exportar os dados (já que o Manager conhece esse dado).

**Comment by leticiaquino** [comment]
@gustavofonseca em `<journal-meta>` podemos considerar então apenas o `<issn>`, conforme conversamos na reunião passada?

**Comment by gustavofonseca** [comment]
~~O elemento <issn> é suficiente para identificar o periódico, então podemos sim desobrigar o preenchimento dos outros campos relacionados ao periódico.~~

Correção:
  O elemento <issn> **não** é suficiente para identificar o periódico.

**Comment by gustavofonseca** [comment]
Será que não é um momento oportuno para começar a suportar **issn-l**? http://jats.nlm.nih.gov/publishing/tag-library/1.1d1/n-6240.html

**Comment by fabiobatalha** [comment]
Acho que seria talvez o momento oportuno para gerarmos um ID SciELO para os periódicos das nossas coleções e exigir que os XML's enviados para o SciELO por prestadoras e afins utilizassem esse ID SciELO.

**Comment by gustavofonseca** [comment]
Resolvido em https://github.com/scieloorg/packtools/issues/3
