### ISSUE TITLE
PackageAnalyzer quebra em caso de exceções na leitura do pacote 

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/balaio#28]
A biblioteca não trata casos onde o pacote não é um arquivo zip válido, não é um arquivo válido, não tem permissão de leitura e outros erros que podem ocorrer na leitura de arquivos.

**Comment by jamilatta** [comment]
Reavaliando se o código contempla essas características.

**Comment by gustavofonseca** [comment]
Precisa criar os testes automáticos para todos esses casos de teste

**Comment by jamilatta** [comment]
Essa necessidade está sendo contemplado no ticket #29.
