### ISSUE TITLE
Avaliar e incorporar os testes do XML-RPC, do ticket #275

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/balaio#286]
Ver #275

**Comment by jamilatta** [comment]
Ticket duplicado, ver: #276.

**Comment by gustavofonseca** [comment]
Tem certeza?

## 

-Gustavo

**Comment by jamilatta** [comment]
Sim.

On Mon, Mar 24, 2014 at 10:48 AM, Gustavo Fonseca
notifications@github.comwrote:

> Tem certeza?
> 
> ## 
> 
> -Gustavo
> 
> On Mon, Mar 24, 2014, at 06:45 AM, Jamil Atta Junior wrote:
> 
> > Ticket duplicado: #276.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/scieloorg/balaio/issues/286#issuecomment-38445423
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/scieloorg/balaio/issues/286#issuecomment-38445756
> .

## 

Atenciosamente,

Jamil Atta Junior

**Comment by gustavofonseca** [comment]
"Avaliar e incorporar os testes" de um determinado endpoint me parece
diferente de "Avaliar infra estrutura de testes" de um módulo.

## 

-Gustavo

**Comment by jamilatta** [comment]
Um implica no outro, mas se mesmo assim acredita que é diferente, é so
reabrir.

On Mon, Mar 24, 2014 at 11:04 AM, Gustavo Fonseca
notifications@github.comwrote:

> "Avaliar e incorporar os testes" de um determinado endpoint me parece
> diferente de "Avaliar infra estrutura de testes" de um módulo.
> 
> ## 
> 
> -Gustavo
> 
> On Mon, Mar 24, 2014, at 06:54 AM, Jamil Atta Junior wrote:
> 
> > Sim.
> > 
> > On Mon, Mar 24, 2014 at 10:48 AM, Gustavo Fonseca
> > notifications@github.comwrote:
> > 
> > > Tem certeza?
> > > 
> > > ## 
> > > 
> > > -Gustavo
> > > 
> > > On Mon, Mar 24, 2014, at 06:45 AM, Jamil Atta Junior wrote:
> > > 
> > > > Ticket duplicado: #276.
> > > > 
> > > > ---
> > > > 
> > > > Reply to this email directly or view it on GitHub:
> > > > https://github.com/scieloorg/balaio/issues/286#issuecomment-38445423
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/scieloorg/balaio/issues/286#issuecomment-38445756>
> > > .
> > 
> > ## 
> > 
> > Atenciosamente,
> > 
> > Jamil Atta Junior
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/scieloorg/balaio/issues/286#issuecomment-38446514
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/scieloorg/balaio/issues/286#issuecomment-38447761
> .

## 

Atenciosamente,

Jamil Atta Junior
