### ISSUE TITLE
ícone de identificação de erro com problemas

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/balaio#289]
Em "List of Check-ins by Article:" os arquivos BWHO estão com o ícone como "ok":

![balaioo](https://f.cloud.github.com/assets/4397365/2526441/9bb422da-b4fa-11e3-8c63-a737d7b7fdd5.jpg)

Porém ao entrar em detalhes há identificações de erros e alertas. veja:

![balaioi](https://f.cloud.github.com/assets/4397365/2526456/bedf9e42-b4fa-11e3-91b4-d5a6cd40ec47.jpg)

Isso acontece com todos os arquivos da BWHO:

http://homolog.manager.scielo.org/arttrack/
http://homolog.manager.scielo.org/arttrack/notice/62/

**Comment by gustavofonseca** [comment]
@leticiaquino, não consegui reproduzir o erro. Vamos avaliar o motivo da divergência.

![screen shot 2014-03-26 at 14 15 06](https://f.cloud.github.com/assets/161335/2527932/4c08d20c-b50a-11e3-9218-5ff0b8a9f54e.png)
