### ISSUE TITLE
validação de dados de journal-meta incorreta

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/balaio#292]
Verificamos que o programa apresenta erro em alguns dados de `<journal-meta>`, porém não foi constatado erro no arquivo.

Note que para o arquivo "0034-8910-rsp-47-06-01021" não foi identificado erro algum. O arquivo foi validado com sucesso. 
http://homolog.manager.scielo.org/arttrack/notice/53/

Porém para os demais arquivos desse fascículo que possuem a mesma estrutura de  `<journal-meta>` foi apresentado os seguintes erros:

**Article   error   Mismatched data: Rev Saude Publica. Expected:**
**Article   error   Missing data: abbrev-journal-title**

Veja:
http://homolog.manager.scielo.org/arttrack/notice/59/
http://homolog.manager.scielo.org/arttrack/notice/55/
http://homolog.manager.scielo.org/arttrack/notice/54/

**Comment by gustavofonseca** [comment]
O caso da URL de final:
- /notice/53/ : Essa validação falhou na verdade por falta do registro do fascículo no manager, pode ver que só há 1 mensagem dizendo **Attempt ready to be validated**. Esse caso já foi corrigido mas o registro ficou perneta.
- /notice/59/ : O _short title_ está errado mesmo.. o correto é **Rev. Saúde Pública**. A mensagem deveria ser mais clara sobre isso.
- /notice/55/ : Ídem ao anterior.
- /notice/54/ : Ídem ao anterior.

**Comment by gustavofonseca** [comment]
Ops, ignore meu comentário anterior... não é o _short title_ que está sendo validado.

**Comment by gustavofonseca** [comment]
A mensagem: `Mismatched data: Rev Saude Publica. Expected:`
Significa que o campo **journal-meta/journal-id[@journal-id-type="nlm-ta"]** contém um valor que não corresponde ao cadastrado no Manager. Na verdade não há valor preenchido para o campo _Título Medline_ para a RSP. O texto está pouco claro, inclusive eu demorei um bocado para identificar o problema... vamos melhorar.

---

A mensagem: `Missing data: abbrev-journal-title`
Significa que estamos fazendo coisa errada, tentando pegar `.//journal-meta/abbrev-journal-title[@abbrev-type="publisher"]` ao invés de `.//journal-meta/journal-title-group/abbrev-journal-title[@abbrev-type="publisher"]`.
