### ISSUE TITLE
Validação do XML do artigo contra a XSD da SciELO

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/balaio#293]
Devemos criar um PIPE para validar o XML perante a XSD da SciELO: http://static.scielo.org/sps/schema/SciELO-journalpublishing1.xsd

**Comment by jamilatta** [comment]
Mais informações, ver: http://www.scielo.org/php/level.php?component=56&item=54&lang=pt

**Comment by gustavofonseca** [comment]
A lib `packtools` possui a essa funcionalidade. No balaio, está exposta em: `PackageAnalyzer().is_valid_schema()` e `PackageAnalyzer().is_valid()`.

**Comment by gustavofonseca** [comment]
Feito no commit [cfc1c6a9d62af80b0fbd5c10d88179d3566623b8]
