### ISSUE TITLE
BUG - Balaio não processou todos os arquivos enviados pelo FTP

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/balaio#306]
O Balaio não processou todos os arquivos enviados via FTP.

Primeiramente foi enviado ao FTP 3 arquivos da GMB (0149; 0147 e 0186),o envio foi efetuado com sucesso, mas em **List of Check-ins by Article** apenas os arquivos 0149 e 0186 subiram.
Em seguida foi enviado os arquivos 0210; 0299; 0305 e 0310, no entando em **List of Check-ins by Article** subiu apenas três arquivos: 0299; 0305 e 0310.

Os arquivos **0147** e **0210** não foram processados. Veja:

No FTP:
![balaio](https://cloud.githubusercontent.com/assets/4397365/2930119/047abee6-d792-11e3-9d4a-3f0865228107.jpg)

No homolog.manager:
![manager](https://cloud.githubusercontent.com/assets/4397365/2930134/40c20cba-d792-11e3-82f1-e38559ec1d86.jpg)

**Comment by gustavofonseca** [comment]
O balaio está apresentando problemas no processamento de suplementos.

**Comment by leticiaquino** [comment]
@jamilatta subi 4 arquivos da gmb (suplemento): .0147, .0171 .0210, .0241, porém no homolog.manager subiu apenas 1 arquivo: 0241.

Enviei também para o FTP outros 2 arquivos da gmb que não tem informação de suplemento em `<issue>`, .0263 e .0271. Esses arquivos subiram. Veja: http://homolog.manager.scielo.org/arttrack/

**Comment by gustavofonseca** [comment]
Só para avisar: O bug foi resolvido entretanto as instâncias ainda não foram atualizadas.

**Comment by gustavofonseca** [comment]
Agora está atualizado.

**Comment by jamilatta** [comment]
Foi realizado os ajustes na API do manager para garantir a busca de fascículos do tipo suplemento de volume e suplemento de fascículo, reparem: https://github.com/scieloorg/scielo-manager/pull/791, porém isso não foi suficiente para resolver o problema, existe outras característica no XML que devemos atender, essas características estão descritas no tk: https://github.com/scieloorg/balaio/issues/309
