### ISSUE TITLE
Criar endpoint para receber notificação de pacotes expirados no SciELO Manager

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/balaio#315]

**Comment by gustavofonseca** [comment]
O que significa _expirar um pacote_ ? Eu imagino que seja:
- Remover o arquivo .zip do disco
- Marcar o Attempt relacionado com uma flag de `expired`

Após isso, a função `proceed_to_checkout` (RPC) deve garantir que não seja possível realizar checkout de Attempts expirados.

**Comment by gustavofonseca** [comment]
Também não deve ser possível expirar um pacote que já foi enviado para checkout.

**Comment by jfunez** [comment]
:+1:

**Comment by jamilatta** [comment]
Concordo.

**Comment by fabiobatalha** [comment]
Sumemo.
