### ISSUE TITLE
Criar conta de FTP para entrada de pacotes

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/balaio#4]

**Comment by jamilatta** [comment]
Verificado com a equipe de infra-estrutura o cenário atual do FTP SciELO:

Atualmente o FTP garante que o usuário tem acesso somente a uma pasta especifica. As permissões são determinadas no arquivo de configuração do próprio FTP (atualmente a mascara é: 022).

Nessas condição acreditamos que seja interessante **remover** a permissão de escrita do **dono** e de **outro** e alterar o grupo do arquivo, dessa forma garantirmos que o arquivo não será modificado durante sua análise.

**Comment by gustavofonseca** [comment]
documentado em wiki.scielo.local
