### ISSUE TITLE
Verificar e documentar regras de criação de contas de FTP e permissões.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/balaio#7]
Permitir que o usuário tenha apenas a permissão de copiar arquivos novos, não podendo remove-los ou edita-los uma vez que já foram copiados para o FTP.

**Comment by fabiobatalha** [comment]
1. Todos fornecedores de pacotes de artigos deverão ter uma conta de FTP para carga de pacotes.
2. As contas deverão ser criadas em nome de empresas, instituições ou parceiros, ex:
   - scielo.caboverde
   - scielo.charlesworth
   - scielo.scielo_br
   - scielo.scielo_org_ar
3. Não serão criadas contas de FTP para usuários individuais de cada instituição, ex:
   - scielo.caboverde.user1
   - scielo.caboverde.user2
4. Cada conta de FTP terá um diretório exclusivo para o depósito de pacotes.
5. Somente serão aceitos pacotes com extensão **.zip**
6. Pacotes fora das características acordadas serão automaticamente excluídos do FTP.
7. A conta de FTP não poderá ser utilizada para nenhuma outra finalidade diferente do depósito de pacotes de artigos.

**Comment by gustavofonseca** [comment]
É importante garantir que estes parágrafos estejam no documento de
especificação do Drive

2013/5/16 Fabio Batalha notifications@github.com

**Comment by fabiobatalha** [comment]
Sim, eu vou colocar lá

2013/5/16 Gustavo Fonseca notifications@github.com
