### ISSUE TITLE
Idéias para a especificação do Gateway HTTP

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/balaio#80]
1. Quais as funcionalidades a serem expostas para o SciELO Manager
2. Segurança
3. Requisitos não-funcionais
4. Documentação de API
5. Prova de conceito
6. Frameworks disponíveis

**Definições:**

**Premissas:**
- Essa API estará disponível apenas internamente(intranet).

**Funcionalidades do Gateway HTTP** 

| Funcionalidade | Descrição | Parâmetros | Recurso | Métodos | Retorno |
| :-: | :-- | :-: | :-: | :-: | :-: |
| Inspecionar o pacote SPS e RSPS válidos ou inválidos. | Permitir que os usuários possam obter os pacotes que desejam para identificar ajustes ou erros. | id ou checksum do pacote. | /packages/ /packages/:id/ | GET | Download do pacote comprimido. |
| Obter informações isoladas de cada pacote. | Através do id do pacote retornar suas tentativas. | id do pacote. | /attempts/ /attempts/:id | GET | Lista com links para as tentativas. |
| Histórico de validação por tentativa. | Permitir que através da tentativa seja visualizado as validações e status de cada etapa possibilitando rastreabilidade. | id da tentativa. | /attempts/ /attempts/:id | GET | Lista com as etapas e seus status. |
| Abrir ticket para corrigir o pacote | Quando o pacote tem algumas pendências, o usuário da equipe de produção pode abrir um ticket solicitando as correções que são necessárias. | id do pacote | /ticket/ /ticket/:id/ | PUT |  |
| Fechar ticket | Quando o pacote tem as pendências resolvidas, o usuário da equipe de produção pode fechar o ticket. | id do ticket | /ticket/ /ticket/:id/ | PUT |  |

**Obs**.: Observem que a coluna **retorno** está em alto nível, estou colocando necessidades futuras do cliente HTTP, a forma como o Gateway irá disponibilizar esses dados estará documentado na API.

A coluna **Recurso** é padrão, portanto, falta adicionar e avaliar os parâmetros opcionais.

---

**Segurança**

Perante as respostas e discussões realizadas pela equipe, ficou decidido que a segurança REST fica restrita a um **basic autentication**, lembrando que a maioria das requisições serão métodos GET.

---

**Requisitos não-funcionais do Gateway HTTP**

| REF | Requisito | Descrição | Qualidade |
| :-: | :-: | :-: | :-: |
| RNF-001 | Disponibilidade | Uptime semanal de 99,97% (Downtime: 30 minutos) |  |
| RNF-002 | Performance | Deve atender 6000rpm | 95% das reqs<=600ms |
| RNF-003 | Eficiência-Mem | <=500MB consumo total(app) | 98% do tempo<=500MB |
| RNF-004 | Robustez | Para todas as requisições deve haver uma resposta HTTP |  |
| RNF-005 | Escalabilidade | Capacidade de rodar N processos |  |

Links interessantes sobre requisitos não funcionais:

http://www.scaledagileframework.com/nonfunctional-requirements/
http://en.wikipedia.org/wiki/Non-functional_requirement
http://broadcast.oreilly.com/2010/02/nonfunctional-requirements-how.html
http://leadinganswers.typepad.com/files/non-functional-requiements.pdf
http://codesqueeze.com/the-7-software-ilities-you-need-to-know/

---

**Documentação**

http://docs.scielo.org/projects/balaio/en/latest/

---

**Prova de conceito em Pyramid**

Gist:  https://gist.github.com/jamilatta/6463527

**Comment by jamilatta** [comment]
Criado documentação, disponível em: http://docs.scielo.org/projects/balaio/en/latest/dev/gateway_http_api.html
