### ISSUE TITLE
Atributo *Attempt.collection_uri* não é utilizado e deve ser removido.

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/balaio#86]
No models.py, ArticlePkg não contém a identificação de coleção, mas em Attempt, sim. 

Quando e como identificar a que coleção o pacote do artigo irá? pelos fascículos disponíveis nas coleções?

**Comment by gustavofonseca** [comment]
Na realidade nenhum tipo de entidade, no contexto do balaio, deveria precisar saber qual a coleção que o pacote pertence. Caso seja necessário consultar algum dado referencial, o atributo _Attempt.checkin_uri_ contém a URI que representa o Attempt no Manager.

**Comment by jamilatta** [comment]
Alguém deseja se manifestar sobre essa discussão, caso contrário, irei realizar a remoção desse atributo.

**Comment by gustavofonseca** [comment]
Pode remover.

## 

-Gustavo

**Comment by jamilatta** [comment]
Item removido.
