### ISSUE TITLE
Criar endpoint Tickets

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/balaio#93]
Criar o endpoint tickets seguindo a documentação disponível em: http://docs.scielo.org/projects/balaio/en/latest/dev/tickets-api.html

**Comment by jamilatta** [comment]
Criado os endpoints para o método GET, está sendo estudado e desenvolvido os endpoints para PATCH  e PUT.

**Comment by gustavofonseca** [comment]
Vc quer dizer que foi implementado o método _GET_ para o endpoint **tickets** e ainda faltam os métodos _PATCH_ e _PUT_, certo?

**Comment by jamilatta** [comment]
Isso.

On Wed, Sep 18, 2013 at 11:33 AM, Gustavo Fonseca
notifications@github.comwrote:

> Vc quer dizer que foi implementado o método _GET_ para o endpoint *tickets
> - e ainda faltam os métodos _PATCH_ e _PUT_, certo?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/scieloorg/balaio/issues/93#issuecomment-24668632
> .

## 

Atenciosamente,

Jamil Atta Junior
